swagger: '2.0'
info:
  description: This is an Node-service
  version: 1.0.0
  title: Swagger Node-service
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: Jerry.x.wang@newegg.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:3000
basePath: /v1
tags:
  - name: Customer
    description: Customer operation
schemes:
  - https
  - http
paths:
  /api/users/register:
    post:
      tags:
        - Customer
      summary: Register new user
      description: Register new user
      operationId: CustomerRegister
      produces:
        - application/xml
        - application/json      
      parameters: 
        - in: body
          name: body
          description: Create customer operation
          required: true
          schema:
            $ref: '#/definitions/Customer'
      responses:
        default:
          description: successful operation
  /api/users/login:
    post:
      tags:
        - Customer
      summary: Login a customer
      description: Login user
      operationId: CustomerLogin
      produces:
        - application/xml
        - application/json      
      parameters: 
        - in: body
          name: body
          description: Login customer operation
          required: true
          schema:
            $ref: '#/definitions/LoginRequest'
      responses:
        default:
          description: successful operation          
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Customer:
    type: object
    properties:
      id:
        type: string
      loginName:
        type: string
      name:
        type: string
      phone:
        type: string
      email:
        type: string
      password:
        type: string
      avatar:
        type: string
      inDate:
        type: string  
      editDate:
        type: string
      editUser:
        type: string
      companyCode:
        type: integer
        format: int32
      countryCode:
        type: string
      languageCode:
        type: string
  LoginRequest: 
    type: object
    properties:
      loginName:
        type: string
      password:
        type: string
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      status:
        type: boolean
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
